### ISSUE TITLE
Ida 7.7 show error name 'AS_NOTAB' is not defined

### ISSUE THREAD

**Issue by joroMaser** [themadinventor/ida-xtensa#21]
```
PROCESSOR_ENTRY: C:\Program Files\IDA Pro 7.7\procs\xtensa.py: name 'AS_NOTAB' is not defined
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.7\python\3\ida_idaapi.py", line 612, in IDAPython_LoadProcMod
    procmod = imp.load_module(procmod_name, fp, pathname, description)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python37\Lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python37\Lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Program Files/IDA Pro 7.7/procs\xtensa.py", line 201, in <module>
    class XtensaProcessor(processor_t):
  File "C:/Program Files/IDA Pro 7.7/procs\xtensa.py", line 215, in XtensaProcessor
    | AS_ASCIIC | AS_ASCIIZ,
NameError: name 'AS_NOTAB' is not defined
```

**Comment by TakenTo** [comment]
I also encountered the same bug, my software version is IDA_Pro_v8.3

**Comment by DeePunk42** [comment]
It seems that it`s just a flag to control texts alignment, I added the line at the head of it:
```python
AS_NOTAB = 0x0001
```
and it works

**Comment by TakenTo** [comment]
> It seems that it`s just a flag to control texts alignment, I added the line at the head of it:
> 
> ```python
> AS_NOTAB = 0x0001
> ```
> 
> and it works

Thank you for solving my problem
